name: build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Fetch dependencies
      run: go get ./...

    - name: Test
      run: |
        go test -race -v ./... -covermode=atomic -coverprofile=coverage.out
        go tool cover -func=coverage.out -o=coverage.out

    - name: Go Coverage Badge
      uses: tj-actions/coverage-badge-go@v1.2
      with:
        filename: coverage.out
        text: coverage

    - name: Verify Changed files
      uses: tj-actions/verify-changed-files@v9.1
      id: verify-changed-files
      with:
        files: README.md

    - uses: stefanzweifel/git-auto-commit-action@v4
      id: auto-commit-action
      with:
        commit_message: docs(readme): update coverage badge
        skip_fetch: true
        skip_checkout: true
        file_pattern: ./README.md

    - name: Push changes
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ github.token }}
        branch: ${{ github.head_ref }}
